#!/bin/bash

# SNMP Data Collection Script for FCX/ICX Switches
# Usage: ./collect_snmp_data.sh <ip_address> <community> <device_name>

set -e  # Exit on any error

# Check if snmp tools are installed
if ! command -v snmpget &> /dev/null; then
    echo "ERROR: snmpget not found. Please install snmp tools:"
    echo "  Ubuntu/Debian: sudo apt-get install snmp"
    echo "  CentOS/RHEL: sudo yum install net-snmp-utils"
    exit 1
fi

if ! command -v snmpwalk &> /dev/null; then
    echo "ERROR: snmpwalk not found. Please install snmp tools."
    exit 1
fi

# Validate arguments
if [ $# -ne 3 ]; then
    echo "Usage: $0 <ip_address> <community> <device_name>"
    echo "Example: $0 172.16.255.5 vweb-ro icx6450"
    exit 1
fi

IP_ADDRESS="$1"
COMMUNITY="$2"
DEVICE_NAME="$3"

# Create output directory
OUTPUT_DIR="snmp_data"
mkdir -p "$OUTPUT_DIR"

# Generate timestamp
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_FILE="${OUTPUT_DIR}/${DEVICE_NAME}_${TIMESTAMP}.txt"
ERROR_FILE="${OUTPUT_DIR}/${DEVICE_NAME}_${TIMESTAMP}_errors.txt"

# SNMP options
SNMP_VERSION="2c"
SNMP_TIMEOUT="10"  # 10 seconds timeout
SNMP_RETRIES="3"

# Function to run snmpget with error handling
run_snmpget() {
    local oid="$1"
    local description="$2"

    echo "=== $description ===" >> "$OUTPUT_FILE"
    echo "OID: $oid" >> "$OUTPUT_FILE"

    if snmpget -v "$SNMP_VERSION" -c "$COMMUNITY" -t "$SNMP_TIMEOUT" -r "$SNMP_RETRIES" "$IP_ADDRESS" "$oid" >> "$OUTPUT_FILE" 2>> "$ERROR_FILE"; then
        echo "SUCCESS" >> "$OUTPUT_FILE"
    else
        echo "FAILED" >> "$OUTPUT_FILE"
        echo "ERROR: Failed to get $description ($oid) from $IP_ADDRESS" >> "$ERROR_FILE"
    fi
    echo "" >> "$OUTPUT_FILE"
}

# Function to run snmpwalk with error handling
run_snmpwalk() {
    local oid="$1"
    local description="$2"
    local max_entries="${3:-50}"  # Default max 50 entries

    echo "=== $description ===" >> "$OUTPUT_FILE"
    echo "OID: $oid" >> "$OUTPUT_FILE"

    if snmpwalk -v "$SNMP_VERSION" -c "$COMMUNITY" -t "$SNMP_TIMEOUT" -r "$SNMP_RETRIES" "$IP_ADDRESS" "$oid" 2>> "$ERROR_FILE" | head -n "$max_entries" >> "$OUTPUT_FILE"; then
        echo "SUCCESS (showing first $max_entries entries)" >> "$OUTPUT_FILE"
    else
        echo "FAILED" >> "$OUTPUT_FILE"
        echo "ERROR: Failed to walk $description ($oid) from $IP_ADDRESS" >> "$ERROR_FILE"
    fi
    echo "" >> "$OUTPUT_FILE"
}

echo "Starting SNMP data collection for $DEVICE_NAME ($IP_ADDRESS) at $(date)"
echo "Output file: $OUTPUT_FILE"
echo "Error file: $ERROR_FILE"
echo ""

# Initialize output files
echo "# SNMP Data Collection for $DEVICE_NAME" > "$OUTPUT_FILE"
echo "# IP Address: $IP_ADDRESS" >> "$OUTPUT_FILE"
echo "# Community: $COMMUNITY" >> "$OUTPUT_FILE"
echo "# Timestamp: $(date)" >> "$OUTPUT_FILE"
echo "# Generated by collect_snmp_data.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "# SNMP Errors for $DEVICE_NAME" > "$ERROR_FILE"
echo "# IP Address: $IP_ADDRESS" >> "$ERROR_FILE"
echo "# Timestamp: $(date)" >> "$ERROR_FILE"
echo "" >> "$ERROR_FILE"

# System Information
echo "Collecting System Information..."
run_snmpget "1.3.6.1.2.1.1.1.0" "System Description (sysDescr)"
run_snmpget "1.3.6.1.2.1.1.2.0" "System Object ID (sysObjectID)"
run_snmpget "1.3.6.1.2.1.1.3.0" "System Uptime (sysUpTime)"
run_snmpget "1.3.6.1.2.1.1.5.0" "System Name (sysName)"
run_snmpget "1.3.6.1.2.1.1.6.0" "System Location (sysLocation)"
run_snmpget "1.3.6.1.2.1.1.4.0" "System Contact (sysContact)"

# Foundry/Brocade Stack Information
echo "Collecting Stack Information..."
run_snmpget "1.3.6.1.4.1.1991.1.1.2.1.1.0" "Stack Member Count (snStackMemberCount)"
run_snmpwalk "1.3.6.1.4.1.1991.1.1.2.1.2" "Stack Member Table (snStackMemberTable)" 100
run_snmpget "1.3.6.1.4.1.1991.1.1.2.1.3.0" "Stack Port Count (snStackPortCount)"
run_snmpwalk "1.3.6.1.4.1.1991.1.1.2.1.4" "Stack Port Table (snStackPortTable)" 50

# Stack Member Details (for members 1-8)
echo "Collecting Stack Member Details..."
for member_id in {1..8}; do
    echo "  Member $member_id..."
    run_snmpget "1.3.6.1.4.1.1991.1.1.2.1.2.1.1.$member_id" "Stack Member $member_id ID"
    run_snmpget "1.3.6.1.4.1.1991.1.1.2.1.2.1.2.$member_id" "Stack Member $member_id Type"
    run_snmpget "1.3.6.1.4.1.1991.1.1.2.1.2.1.3.$member_id" "Stack Member $member_id Status"
    run_snmpget "1.3.6.1.4.1.1991.1.1.2.1.2.1.4.$member_id" "Stack Member $member_id MAC Address"
    run_snmpget "1.3.6.1.4.1.1991.1.1.2.1.2.1.5.$member_id" "Stack Member $member_id Priority"
done

# Hardware Information
echo "Collecting Hardware Information..."
run_snmpget "1.3.6.1.4.1.1991.1.1.1.1.1.1" "Chassis Unit 1 (snChasUnit)"
run_snmpget "1.3.6.1.4.1.1991.1.1.1.1.2.1" "Chassis Serial Number (snChasSerNum)"
run_snmpwalk "1.3.6.1.4.1.1991.1.1.1.1.7" "Power Supply Information (snChasPwrSupplyTable)" 10

# Entity MIB - Physical Inventory
echo "Collecting Entity MIB Information..."
run_snmpwalk "1.3.6.1.2.1.47.1.1.1" "Entity Physical Table (entPhysicalTable)" 100

# Interface Information (first few interfaces)
echo "Collecting Interface Information..."
run_snmpwalk "1.3.6.1.2.1.2.2" "Interface Table (ifTable)" 50

# Additional Foundry-specific information
echo "Collecting Additional Foundry Information..."
run_snmpwalk "1.3.6.1.4.1.1991.1.1.3" "Foundry Agent Configuration" 20
run_snmpwalk "1.3.6.1.4.1.1991.1.1.4" "Foundry Interface Extensions" 20

echo "" >> "$OUTPUT_FILE"
echo "# Collection completed at $(date)" >> "$OUTPUT_FILE"

# Check if error file has content
if [ -s "$ERROR_FILE" ]; then
    echo ""
    echo "WARNING: Some SNMP queries failed. Check $ERROR_FILE for details."
else
    rm "$ERROR_FILE"  # Remove empty error file
fi

echo ""
echo "SNMP data collection completed!"
echo "Output saved to: $OUTPUT_FILE"
echo ""
echo "Summary:"
echo "- Device: $DEVICE_NAME"
echo "- IP: $IP_ADDRESS"
echo "- Lines collected: $(wc -l < "$OUTPUT_FILE")"

# Show a brief summary of what was collected
echo ""
echo "Collection Summary:"
echo "==================="
grep "^=== " "$OUTPUT_FILE" | sed 's/^=== //' | sed 's/ ===//' | head -10

echo ""
echo "Run the following commands to analyze the data:"
echo "  less $OUTPUT_FILE"
echo "  grep 'FAILED' $OUTPUT_FILE || echo 'All queries successful'"